json.id         user.id
json.email      user.email
json.name       user.full_name
json.username   user.username
json.first_name user.first_name
json.last_name  user.last_name
json.uid        user.uid
json.provider   user.provider
json.document   user.document
json.birthday   user.birthday
json.user_type  user.user_type
json.created_at user.created_at
json.updated_at user.updated_at
